name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      testpypi:
        description: 'Publish to TestPyPI instead of PyPI'
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.testpypi == 'true' && 'testpypi' || 'pypi' }}
      url: ${{ github.event.inputs.testpypi == 'true' && 'https://test.pypi.org/p/divere' || 'https://pypi.org/p/divere' }}
    permissions:
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip build wheel setuptools
        
    - name: Build packages
      run: |
        python -m build --sdist --wheel --outdir dist/
        
    - name: Verify build
      run: |
        ls -la dist/
        python -m pip install dist/*.whl
        python -c "import divere; print(f'DiVERE version: {divere.__version__}')"
        
    - name: Publish to TestPyPI
      if: github.event.inputs.testpypi == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        
    - name: Publish to PyPI
      if: github.event.inputs.testpypi != 'true'
      uses: pypa/gh-action-pypi-publish@release/v1